### ISSUE TITLE
Unhandled Promise rejection: Failed to execute 'postMessage' on 'Window'

### ISSUE THREAD

**Issue by LemonGeu** [taarskog/crm-powerbi-viewer#34] opened 2018-08-31 13:16 UTC
Hello,

I'm using your powerbi viewer but since a couple of days I get this error message.
I'm use a javascript to filter out a specific account. I can still see the report but it doesn't get filtered anymore.

Any solutions?
![filtercustomer](https://user-images.githubusercontent.com/42868622/44914489-b5818580-ad30-11e8-9ced-1d11d01583d8.png)

Kind regards,

Lemon

**Comment by christinaa7** [comment] 2018-08-31 13:30
I have the same issue.

Regards,
Christina

**Comment by taarskog** [comment] 2018-08-31 13:31
Hi Lemon and Christina,

Can you tell me:
1. Is it D365CE on-premises or Online
1. What version of D365CE...
1. and crm-powerbi-viewer are you on?
1. Did it start happening after a change to the javascript and/or did you modify the form where it is embedded?

**Comment by christinaa7** [comment] 2018-08-31 13:39
Hello taarskog,

thank you for your quick response.
1. D365 Online 
2. 9.0.2.1470
3. first we had the version 0.5 and I updated to version 1.1.0
4. I don't know when it starts, but we changed nothing neither JavaScript nor a form.

**Comment by LemonGeu** [comment] 2018-08-31 14:27
Hello Trond,

First case
1. D365 Online
2. 9.0.2.1470
3.  version 1.0.0
4. Didn't change anything.

Seconde case
1. D365 Online
2. 9.0.2.1468
3.  version 1.1.0
4. Didn't change anything.

Looking forward to your response.
Thanks alot!

Lemon

**Comment by jamesrus1986** [comment] 2018-08-31 16:54
Hi Taarskog,

Here to report the same issue.

1. On-premise.
2. 8.2.2
3. V1.1.0
4. No changes to implementation of solution config, this started today.

Issue reproduceavle in Chrome > latest , but not Firefox. 

Error is the same as above, except this element “Cannot read property: ‘isDeprecated’ of undefined could not be cloned”.

Error occurs at the setting filters step.

Many thanks,
James

**Comment by taarskog** [comment] 2018-08-31 21:45
Looks like the Power BI team may have introduced a bug (or *"feature"* ;-))

In my tests I initially tried to set a filter on the event **_pagechanged_**. As you I also got the promise rejection.

The fix that worked for me was to add an empty call to **setFilters** on the event **loaded**. The call does not need to contain an actual filter but it seems to initialize objects that are required when setting filters on **_pageChanged_**.

Appreciate if you can help verify by adding the following to your code (adjust names etc. to match your code):

```
Samples.Filters.filterOnUser = function(report) {
   report.on("loaded", function(event) {
      report.setFilters();

      ... Original code triggering on pageChanged  ...
   });
}
```

**Comment by LemonGeu** [comment] 2018-09-01 09:52
Hello Trond,

I tried to setFilters on loaded event. But for the v1.0 and the v1.1.0 version I get same errors.
Also if I change a page afterwards I get the first error message again since the page is already loaded at that point.

![setfilter](https://user-images.githubusercontent.com/42868622/44944789-680f2200-addd-11e8-954f-b4e0b88724ad.png)
![filter](https://user-images.githubusercontent.com/42868622/44944792-6b0a1280-addd-11e8-90fd-49e7735c6af2.png)

What should I change in the script?

Lemon

**Comment by taarskog** [comment] 2018-09-01 11:32
Hi Lemon,

Did you clear the cache and increase the script file version in the config file (e.g. `?ver=2`)? Suggest you also add a `console.log` right after setting the empty filter to verify that you are executing the most recent code changes.

-Trond

**Comment by LemonGeu** [comment] 2018-09-01 16:38
Hi Trond,

I did clear cache + tried incognito browser. Also from what I can see the '?ver=x' isn't needed at this moment. But I did use it now with still no succes. I get "empty filter" in the console log written by console.log.

Lemon

**Comment by taarskog** [comment] 2018-09-01 21:38
Hi Lemon,

Thank you for testing. Unfortunately I made a mistake Yesterday when I provided the code above. The empty call to setFilters require an empty array: `report.setFilters([]);`.

Though I believe using `report.removeFilters();` may be a better function to use. Both approaches are working in my environments.

![image](https://user-images.githubusercontent.com/609765/44950124-fb793f00-ae3f-11e8-9e58-24d6242e375e.png)

-Trond

**Comment by LemonGeu** [comment] 2018-09-02 16:11
Hi Trond,

removeFilters() did indeed fix the errors. The scripts loads and triggers the pageChanged.

At this moment it doesn't filter my first page (that is not changed) before it did it. I didn't manage to get it working on page load yet. Do you have any idea how to trigger to get my first loaded page filtered aswell?

Anyways alot of thanks for the quick support!

Lemon

**Comment by christinaa7** [comment] 2018-09-03 13:12
Hello Trond,

thank you for your prompt solution.
It works by changing the report page, but not on initial load.
Before this bug/feature (we will never know) it worked fine.
Maybe is there antoherway to trigger it?

Or is there an error in my code?

```
Samples.Filters.filterOnAccount = function (report) {
    report.on("loaded", function(loadedEvent) {
        console.log("Report loaded");
		
		console.log("Remove filters on report");
		report.removeFilters();
		
		report.on("pageChanged", function(event) {
			let page = event.detail.newPage;
			console.log(`Page changed to '${page.displayName}' (${page.name})`);

			var firma = window.parent.Xrm.Page.data.entity.getId();
			firma = firma.replace('{', '').replace('}', '');

			console.log("Firma - " + firma); 		
		
			if (page.displayName === "Produktauswertung" || page.displayName === "Jahresauswertung") {
				const filter = {
					$schema: "http://powerbi.com/product/schema#basic",
					target: {
						table: "accounts",
						column: "accountid"
					},
					operator: "In",
					values: [firma]
				};

				page.setFilters([filter]);

			}
		});

	});
}
```

Thank you so much for your help.

Christina

**Comment by taarskog** [comment] 2018-09-03 18:01
Lemon and Christina,

Thanks for providing feedback. Glad to hear it now works.

Regarding setting the initial filter the following seems to work (not sure if it is the right approach though). I'm closing this issue now, but feel free to open another on initial load if my suggestion below does not work.

```javascript
    let filteredSet = false
    report.on('rendered', () => {
        if (filteredSet) return;
        filteredSet = true;
        report.getPages()
        .then(function (pages) {
          // Retrieve active page.
          var activePage = pages.find(function(page) {
            return page.isActive
          });
     
          activePage.setFilters([filter])
            .then(function () {
                console.log("Page filter was set.");
            })
            .catch(function (errors) {
                console.error(errors);
            });
        })
        .catch(function (errors) {
            console.error(errors);
        });
    });
```

**Closed by taarskog** 2018-09-03 18:01 UTC
Labels: bug

**Comment by christinaa7** [comment] 2018-09-04 07:55
Hello Trond,

thanks a lot for you code.
Everything is working fine now.
It's fantastic to get such a great support of an amazing product.

Christina

**Comment by SergioRota** [comment] 2018-09-11 07:46
Hi Trond,

I have the same issue.
I followed these post, modified the web resource, But  the filters don't work.

```
window.Samples = window.Samples || {};
Samples.Filters = Samples.Filters || {};

Samples.Filters.filterOnAccount = function (report) {
 report.on("loaded", function(loadedEvent) {
        console.log("Report loaded");
		
		console.log("Remove filters on report");
		report.removeFilters([]);
		
		report.on("pageChanged", function(event) {
            var page = event.detail.newPage;
        console.log(`Page changed to '${page.displayName}' (${page.name})`);

		var accId = window.parent.Xrm.Page.data.entity.getId();
		accId = accId.replace('{','').replace('}','');

if (page.displayName === "powerbiviewer") {

            const filter = {
                $schema: "http://powerbi.com/product/schema#basic",
                target: {
                    table: "accounts",
                    column: "accountid"
                },
                operator: "In",
                values: [accId]
            };

            page.setFilters([filter]);
        }
    });
	});
}
```

Thanks
Sergio

**Comment by SergioRota** [comment] 2018-09-11 09:51
Hi Trond and Christina,

I have the same issue (filtering on initial load).

Where have I to insert the code: 

```
let filteredSet = false
    report.on('rendered', () => {
        if (filteredSet) return;
        filteredSet = true;
        report.getPages()
        .then(function (pages) {
          // Retrieve active page.
          var activePage = pages.find(function(page) {
            return page.isActive
          });
     
          activePage.setFilters([filter])
            .then(function () {
                console.log("Page filter was set.");
            })
            .catch(function (errors) {
                console.error(errors);
            });
        })
        .catch(function (errors) {
            console.error(errors);
        });
    });
```

in my JS:

```
window.Samples = window.Samples || {};
Samples.Filters = Samples.Filters || {};

Samples.Filters.filterOnAccount = function (report) {


    report.on("loaded", function (loadedEvent) {
        report.removeFilters(); // For some reason this needs to be done before setting page filters (August 2018)

        report.on("pageChanged", function(event) {
            let page = event.detail.newPage;
            console.log(`Page changed to '${page.displayName}' (${page.name})`);

            {
var accId = window.parent.Xrm.Page.data.entity.getId();
accId = accId.replace('{','').replace('}','');               
const filter = {
                    $schema: "http://powerbi.com/product/schema#basic",
                    target: {
                        table: "accounts",
                        column: "accountid"
                    },
                    operator: "In",
                    values: [accId]
                };

                page.setFilters([filter]);
            }
        });
    });
}
```

Thanks
Sergio
